# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jens/C++/ufs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jens/C++/ufs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jens/C++/ufs/CMakeFiles /home/jens/C++/ufs/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jens/C++/ufs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ufs

# Build rule for target.
ufs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ufs
.PHONY : ufs

# fast build rule for target.
ufs/fast:
	$(MAKE) -f src/CMakeFiles/ufs.dir/build.make src/CMakeFiles/ufs.dir/build
.PHONY : ufs/fast

#=============================================================================
# Target rules for targets named ufs_engine

# Build rule for target.
ufs_engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ufs_engine
.PHONY : ufs_engine

# fast build rule for target.
ufs_engine/fast:
	$(MAKE) -f src/engine/CMakeFiles/ufs_engine.dir/build.make src/engine/CMakeFiles/ufs_engine.dir/build
.PHONY : ufs_engine/fast

#=============================================================================
# Target rules for targets named ufs_engine_sprite

# Build rule for target.
ufs_engine_sprite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ufs_engine_sprite
.PHONY : ufs_engine_sprite

# fast build rule for target.
ufs_engine_sprite/fast:
	$(MAKE) -f src/engine/sprite/CMakeFiles/ufs_engine_sprite.dir/build.make src/engine/sprite/CMakeFiles/ufs_engine_sprite.dir/build
.PHONY : ufs_engine_sprite/fast

#=============================================================================
# Target rules for targets named ufs_engine_ui

# Build rule for target.
ufs_engine_ui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ufs_engine_ui
.PHONY : ufs_engine_ui

# fast build rule for target.
ufs_engine_ui/fast:
	$(MAKE) -f src/engine/ui/CMakeFiles/ufs_engine_ui.dir/build.make src/engine/ui/CMakeFiles/ufs_engine_ui.dir/build
.PHONY : ufs_engine_ui/fast

#=============================================================================
# Target rules for targets named ufs_gui_button

# Build rule for target.
ufs_gui_button: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ufs_gui_button
.PHONY : ufs_gui_button

# fast build rule for target.
ufs_gui_button/fast:
	$(MAKE) -f src/gui/button/CMakeFiles/ufs_gui_button.dir/build.make src/gui/button/CMakeFiles/ufs_gui_button.dir/build
.PHONY : ufs_gui_button/fast

#=============================================================================
# Target rules for targets named ufs_gui_window

# Build rule for target.
ufs_gui_window: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ufs_gui_window
.PHONY : ufs_gui_window

# fast build rule for target.
ufs_gui_window/fast:
	$(MAKE) -f src/gui/window/CMakeFiles/ufs_gui_window.dir/build.make src/gui/window/CMakeFiles/ufs_gui_window.dir/build
.PHONY : ufs_gui_window/fast

#=============================================================================
# Target rules for targets named ufs_gui_other

# Build rule for target.
ufs_gui_other: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ufs_gui_other
.PHONY : ufs_gui_other

# fast build rule for target.
ufs_gui_other/fast:
	$(MAKE) -f src/gui/other/CMakeFiles/ufs_gui_other.dir/build.make src/gui/other/CMakeFiles/ufs_gui_other.dir/build
.PHONY : ufs_gui_other/fast

#=============================================================================
# Target rules for targets named ufs_settings

# Build rule for target.
ufs_settings: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ufs_settings
.PHONY : ufs_settings

# fast build rule for target.
ufs_settings/fast:
	$(MAKE) -f src/settings/CMakeFiles/ufs_settings.dir/build.make src/settings/CMakeFiles/ufs_settings.dir/build
.PHONY : ufs_settings/fast

#=============================================================================
# Target rules for targets named ufs_sprite

# Build rule for target.
ufs_sprite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ufs_sprite
.PHONY : ufs_sprite

# fast build rule for target.
ufs_sprite/fast:
	$(MAKE) -f src/sprite/CMakeFiles/ufs_sprite.dir/build.make src/sprite/CMakeFiles/ufs_sprite.dir/build
.PHONY : ufs_sprite/fast

#=============================================================================
# Target rules for targets named ufs_util

# Build rule for target.
ufs_util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ufs_util
.PHONY : ufs_util

# fast build rule for target.
ufs_util/fast:
	$(MAKE) -f src/util/CMakeFiles/ufs_util.dir/build.make src/util/CMakeFiles/ufs_util.dir/build
.PHONY : ufs_util/fast

#=============================================================================
# Target rules for targets named ufs_script

# Build rule for target.
ufs_script: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ufs_script
.PHONY : ufs_script

# fast build rule for target.
ufs_script/fast:
	$(MAKE) -f src/script/CMakeFiles/ufs_script.dir/build.make src/script/CMakeFiles/ufs_script.dir/build
.PHONY : ufs_script/fast

#=============================================================================
# Target rules for targets named ufs_map

# Build rule for target.
ufs_map: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ufs_map
.PHONY : ufs_map

# fast build rule for target.
ufs_map/fast:
	$(MAKE) -f src/map/CMakeFiles/ufs_map.dir/build.make src/map/CMakeFiles/ufs_map.dir/build
.PHONY : ufs_map/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ufs"
	@echo "... ufs_engine"
	@echo "... ufs_engine_sprite"
	@echo "... ufs_engine_ui"
	@echo "... ufs_gui_button"
	@echo "... ufs_gui_window"
	@echo "... ufs_gui_other"
	@echo "... ufs_settings"
	@echo "... ufs_sprite"
	@echo "... ufs_util"
	@echo "... ufs_script"
	@echo "... ufs_map"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

